### ISSUE TITLE
Return codes

### ISSUE THREAD

**Issue by alexandration** [Mcublog/confpoint#1]
Need to add correct return codes. For example, to stop the pipeline when sending or downloading by mistake.

**Comment by Mcublog** [comment]
> Need to add correct return codes. For example, to stop the pipeline when sending or downloading by mistake.

Hi, checkout mcublog/confpoint-docker:latest. Need testing in Ci pipeline

**Comment by Mcublog** [comment]
> Need to add correct return codes. For example, to stop the pipeline when sending or downloading by mistake.

https://pypi.org/project/confpoint/  please check version 1.0.3

**Comment by alexandration** [comment]
>  https://pypi.org/project/confpoint/ please check version 1.0.3

Unfortunately still not working

![image](https://user-images.githubusercontent.com/64081306/177973145-95ad0162-4f0a-4d11-8b5c-7e4735bdcbcf.png)

**Comment by Mcublog** [comment]
Already done some fixes in 1.0.4 version

**Comment by alexandration** [comment]
> Already done some fixes in 1.0.4 version

seems to be done
